"""Base strategy interface for backtesting and live trading."""
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any


class SignalType(str, Enum):
    """Trading signal type."""

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


@dataclass
class Signal:
    """Trading signal generated by a strategy.

    Attributes:
        type: Signal type (BUY, SELL, HOLD).
        market_id: Polymarket condition ID.
        token_id: Token ID for the specific outcome.
        outcome: Outcome name (e.g., "Yes", "No").
        price: Target execution price.
        size: Position size in dollars.
        confidence: Strategy confidence level (0.0 to 1.0).
        timestamp: When the signal was generated.
        stop_loss: Optional stop loss price.
        take_profit: Optional take profit price.
        metadata: Additional signal metadata.
    """

    type: SignalType
    market_id: str
    token_id: str
    outcome: str
    price: float
    size: float
    confidence: float
    timestamp: datetime = field(default_factory=datetime.utcnow)
    stop_loss: float | None = None
    take_profit: float | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Validate signal fields after initialization."""
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(f"Confidence must be between 0 and 1, got {self.confidence}")
        if self.size < 0:
            raise ValueError(f"Size must be non-negative, got {self.size}")
        if not 0.0 <= self.price <= 1.0:
            raise ValueError(f"Price must be between 0 and 1, got {self.price}")


@dataclass
class MarketSnapshot:
    """Point-in-time snapshot of market data for strategy evaluation.

    Attributes:
        market_id: Polymarket condition ID.
        token_id: Token ID for the specific outcome.
        timestamp: Snapshot timestamp.
        yes_price: Current YES token price.
        no_price: Current NO token price.
        yes_bid: Best bid for YES token.
        yes_ask: Best ask for YES token.
        no_bid: Best bid for NO token.
        no_ask: Best ask for NO token.
        spread: Bid-ask spread.
        volume: Recent trading volume.
        volume_24h: 24-hour trading volume.
        open_interest: Total open interest.
        orderbook: Full orderbook data.
        recent_trades: List of recent trades.
        question: Market question text.
        category: Market category.
        end_date: Market end date.
        resolution_rules: Market resolution criteria.
    """

    market_id: str
    token_id: str
    timestamp: datetime
    yes_price: float
    no_price: float
    yes_bid: float | None = None
    yes_ask: float | None = None
    no_bid: float | None = None
    no_ask: float | None = None
    spread: float | None = None
    volume: float = 0.0
    volume_24h: float = 0.0
    open_interest: float | None = None
    orderbook: dict[str, Any] = field(default_factory=dict)
    recent_trades: list[dict[str, Any]] = field(default_factory=list)
    question: str = ""
    category: str | None = None
    end_date: datetime | None = None
    resolution_rules: str | None = None

    @property
    def mid_price(self) -> float:
        """Calculate mid price from bid/ask or use yes_price."""
        if self.yes_bid is not None and self.yes_ask is not None:
            return (self.yes_bid + self.yes_ask) / 2
        return self.yes_price

    @property
    def implied_probability(self) -> float:
        """Return YES price as implied probability."""
        return self.yes_price


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies.

    Strategies implement market analysis logic and generate trading signals.
    They can be used for both backtesting and live trading.

    Example:
        ```python
        class MomentumStrategy(BaseStrategy):
            def on_market_data(self, snapshot: MarketSnapshot) -> Signal | None:
                if snapshot.yes_price > self.config.get("threshold", 0.7):
                    return Signal(
                        type=SignalType.BUY,
                        market_id=snapshot.market_id,
                        token_id=snapshot.token_id,
                        outcome="Yes",
                        price=snapshot.yes_price,
                        size=100.0,
                        confidence=0.8,
                    )
                return None
        ```
    """

    name: str = "base"
    description: str = "Base strategy interface"
    version: str = "1.0.0"

    def __init__(self, config: dict[str, Any] | None = None) -> None:
        """Initialize the strategy with configuration.

        Args:
            config: Strategy-specific configuration parameters.
        """
        self.config = config or {}
        self._is_initialized = False
        self._trade_count = 0
        self._total_pnl = 0.0

    @property
    def is_initialized(self) -> bool:
        """Check if strategy has been initialized."""
        return self._is_initialized

    @abstractmethod
    def on_market_data(self, snapshot: MarketSnapshot) -> Signal | None:
        """Process market data and optionally generate a trading signal.

        This is the main strategy logic method. Called for each market
        data update during backtesting or live trading.

        Args:
            snapshot: Current market state snapshot.

        Returns:
            Signal if a trade should be executed, None otherwise.
        """
        pass

    @abstractmethod
    def calculate_position_size(
        self,
        signal: Signal,
        portfolio_value: float,
        positions: dict[str, Any],
    ) -> float:
        """Calculate the appropriate position size for a signal.

        Implements position sizing logic based on portfolio risk management.

        Args:
            signal: The trading signal to size.
            portfolio_value: Current total portfolio value.
            positions: Dictionary of current open positions.

        Returns:
            Position size in dollars.
        """
        pass

    def on_trade_executed(self, trade: dict[str, Any]) -> None:
        """Called when a trade is successfully executed.

        Override to implement post-trade logic like logging or state updates.

        Args:
            trade: Executed trade details including:
                - market_id: Market identifier
                - token_id: Token traded
                - side: BUY or SELL
                - price: Execution price
                - size: Trade size
                - fee: Transaction fee
                - timestamp: Execution time
        """
        self._trade_count += 1

    def on_position_closed(self, position: dict[str, Any], pnl: float) -> None:
        """Called when a position is closed.

        Override to implement position close logic like performance tracking.

        Args:
            position: Closed position details including:
                - market_id: Market identifier
                - token_id: Token held
                - entry_price: Average entry price
                - exit_price: Exit price
                - size: Position size
                - entry_time: When position was opened
                - exit_time: When position was closed
            pnl: Realized profit/loss in dollars.
        """
        self._total_pnl += pnl

    def reset(self) -> None:
        """Reset strategy state for a new backtest or trading session.

        Called before starting a new backtest run or when restarting
        live trading. Override to reset strategy-specific state.
        """
        self._is_initialized = False
        self._trade_count = 0
        self._total_pnl = 0.0

    async def initialize(self) -> None:
        """Async initialization for loading data or models.

        Override for strategies that need async setup like loading
        ML models or historical data.
        """
        self._is_initialized = True

    async def cleanup(self) -> None:
        """Async cleanup for releasing resources.

        Override for strategies that hold resources like database
        connections or file handles.
        """
        self._is_initialized = False

    def validate_config(self) -> bool:
        """Validate strategy configuration.

        Override to implement config validation logic.

        Returns:
            True if configuration is valid, False otherwise.
        """
        return True

    def get_default_config(self) -> dict[str, Any]:
        """Get default configuration values.

        Override to provide strategy-specific defaults.

        Returns:
            Dictionary of default configuration values.
        """
        return {}

    def get_stats(self) -> dict[str, Any]:
        """Get current strategy statistics.

        Returns:
            Dictionary containing strategy performance stats.
        """
        return {
            "name": self.name,
            "version": self.version,
            "trade_count": self._trade_count,
            "total_pnl": self._total_pnl,
            "is_initialized": self._is_initialized,
        }

    def __repr__(self) -> str:
        """String representation of the strategy."""
        return f"{self.__class__.__name__}(name={self.name}, config={self.config})"
